=== stuckey10/Jinja-Test/dataSchema.xsd
<?xml version = "1.0" encoding="utf-8"?>
<xs:schema
        xmlns:xs="http://www.w3.org/2001/XMLSchema"
        targetNamespace="."
>
  <xs:element name="Data">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Class" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="field" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:string" name="name" use="required"/>
                      <xs:attribute type="xs:string" name="type" use="required"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:string" name="class_name"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== stuckey10/Jinja-Test/data.xml
<?xml version="1.0"?>
<ds:Data xmlns:ds="."
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation=". dataSchema.xsd">
    <Class class_name = "StuckeysTry">
        <field name = "name" type = "string"/>
        <field name = "surname" type = "string"/>
        <field name = "age" type = "int"/>
    </Class>
    <Class class_name = "StuckeysTry2">
        <field name = "name" type = "string"/>
        <field name = "surname" type = "string"/>
        <field name = "age" type = "int"/>
    </Class>
</ds:Data>
